export const REQUEST_THONG_TIN_CA_NHAN = "REQUEST_THONG_TIN_CA_NHAN";
export const SUCCESS_THONG_TIN_CA_NHAN = "SUCCESS_THONG_TIN_CA_NHAN";
export const FAILED_THONG_TIN_CA_NHAN = "FAILED_THONG_TIN_CA_NHAN";

export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
